title: Shervin Sahba's Website.
author: Shervin Sahba
description: Shervin Sahba's personal website.
email: shervinsahba@gmail.com

highlighter: null
permalink: /:title

github username: shervinsahba
url: https://shervinsahba.github.io
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado|seafoam
color_scheme: seafoam
# Jekyll Theme: Brume by Aigars Dzerviniks